import { describe, expect, it } from "vitest";
import {
  computeCandidateSlots,
  filterAvailableSlots,
  minutesToDate,
  overlaps,
} from "../../src/services/slotAlgorithm";

const DAY = new Date(2026, 0, 5); // arbitrary fixed date, local time

describe("computeCandidateSlots", () => {
  it("packs slots back-to-back with duration + buffer step within a window", () => {
    const slots = computeCandidateSlots([{ startMinute: 540, endMinute: 1020 }], DAY, 45, 10);

    expect(slots).toHaveLength(8);
    expect(slots[0]).toEqual({
      start: minutesToDate(DAY, 540),
      end: minutesToDate(DAY, 585),
    });
    expect(slots[1].start).toEqual(minutesToDate(DAY, 595)); // 540 + 45 + 10
    expect(slots.at(-1)!.start).toEqual(minutesToDate(DAY, 925));
  });

  it("supports multiple windows in the same day (e.g. morning + afternoon)", () => {
    const slots = computeCandidateSlots(
      [
        { startMinute: 540, endMinute: 720 }, // 9:00-12:00
        { startMinute: 780, endMinute: 1020 }, // 13:00-17:00
      ],
      DAY,
      60,
      0,
    );

    expect(slots).toHaveLength(3 + 4);
    expect(slots[3].start).toEqual(minutesToDate(DAY, 780));
  });

  it("returns an empty array when there are no availability windows", () => {
    expect(computeCandidateSlots([], DAY, 45, 10)).toEqual([]);
  });

  it("returns an empty array when the window is too short for even one slot", () => {
    const slots = computeCandidateSlots([{ startMinute: 540, endMinute: 560 }], DAY, 45, 10);
    expect(slots).toEqual([]);
  });
});

describe("overlaps", () => {
  it("detects overlapping ranges", () => {
    const a = minutesToDate(DAY, 0);
    expect(overlaps(a, minutesToDate(DAY, 60), minutesToDate(DAY, 30), minutesToDate(DAY, 90))).toBe(
      true,
    );
  });

  it("treats touching boundaries (half-open interval) as non-overlapping", () => {
    expect(
      overlaps(
        minutesToDate(DAY, 0),
        minutesToDate(DAY, 60),
        minutesToDate(DAY, 60),
        minutesToDate(DAY, 120),
      ),
    ).toBe(false);
  });
});

describe("filterAvailableSlots", () => {
  const now = new Date(DAY.getTime() - 24 * 60 * 60 * 1000); // "now" is the day before, so min-notice never trips

  it("removes a candidate that overlaps an existing booking", () => {
    const candidates = computeCandidateSlots([{ startMinute: 540, endMinute: 1020 }], DAY, 45, 10);
    const busy = [{ start: minutesToDate(DAY, 540), end: minutesToDate(DAY, 585) }];

    const result = filterAvailableSlots(candidates, busy, 10, 0, now);

    expect(result.find((s) => s.start.getTime() === minutesToDate(DAY, 540).getTime())).toBeUndefined();
    expect(result).toHaveLength(candidates.length - 1);
  });

  it("extends the buffer around an existing booking even if it wasn't generated by this algorithm", () => {
    // A booking that starts at an odd offset (not aligned to the candidate grid),
    // e.g. added manually by an admin — buffer must still apply on both sides.
    const candidates = computeCandidateSlots([{ startMinute: 540, endMinute: 1020 }], DAY, 45, 10);
    const busy = [{ start: minutesToDate(DAY, 600), end: minutesToDate(DAY, 620) }];

    const result = filterAvailableSlots(candidates, busy, 10, 0, now);

    // candidate at 595-640 overlaps [590,630) busy+buffer range
    expect(result.find((s) => s.start.getTime() === minutesToDate(DAY, 595).getTime())).toBeUndefined();
  });

  it("allows a candidate that starts exactly when the buffered busy range ends", () => {
    const candidates = computeCandidateSlots([{ startMinute: 540, endMinute: 1020 }], DAY, 45, 10);
    // booking 540-585 with 10min buffer -> busy range [530, 595)
    const busy = [{ start: minutesToDate(DAY, 540), end: minutesToDate(DAY, 585) }];

    const result = filterAvailableSlots(candidates, busy, 10, 0, now);

    expect(result.find((s) => s.start.getTime() === minutesToDate(DAY, 595).getTime())).toBeDefined();
  });

  it("excludes candidates that start before the minimum notice window", () => {
    const candidates = computeCandidateSlots([{ startMinute: 540, endMinute: 1020 }], DAY, 45, 10);
    // "now" is 30 minutes before the day starts, with a 60-minute minimum notice
    const almostNow = new Date(minutesToDate(DAY, 540).getTime() - 30 * 60 * 1000);

    const result = filterAvailableSlots(candidates, [], 10, 60, almostNow);

    // earliest bookable = almostNow + 60min = day start + 30min -> first slot (540) excluded, second (595) kept
    expect(result.find((s) => s.start.getTime() === minutesToDate(DAY, 540).getTime())).toBeUndefined();
    expect(result.find((s) => s.start.getTime() === minutesToDate(DAY, 595).getTime())).toBeDefined();
  });
});
